apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-1
  template:
    metadata:
      labels:
        app: api-1
    spec:
      containers:
      - name: api
        image: ghcr.io/sajjadkhan12/datahow-task/datahow-api:latest
        env:
        - name: NAME
          value: "DataHow"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: api-service-1
spec:
  selector:
    app: api-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort