apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-2
  template:
    metadata:
      labels:
        app: api-2
    spec:
      containers:
      - name: api
        image: ghcr.io/sajjadkhan12/datahow-task/datahow-api:latest
        env:
        - name: NAME
          value: "Sajjad Khan"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: api-service-2
spec:
  selector:
    app: api-2
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
  type: NodePort